### PR TITLE
Fix screen edge padding to work properly on HiDPI monitors

### PR DESCRIPTION
**Pull request by goodwillcoding**
Basically just multiple screenPaddingEdge by scale_factor

### CODE REVIEW

**Comment by goodwillcoding** [comment]
@passingthru67 ... bump :-)

**Comment by passingthru67** [comment]
@goodwillcoding I'll merge this in soon.

**Comment by passingthru67** [comment]
@goodwillcoding pull request has been merged. Thanks for the assist.

**Comment by goodwillcoding** [comment]
@passingthru67 no problem,  love the extensions, thank you for it.

**Pull request merged**
