### PR TITLE
Ubuntu dock support. 

### PR DESCRIPTION
**Pull request by DiegoCPB**
The extensions checks for the ubuntu-dock UUID and treats it as an enabled dash-to-dock

### CODE REVIEW

**Comment by DiegoCPB** [comment]
Debug lines were not supposed to be removed

**Comment by passingthru67** [comment]
Okay. Thanks. I'll work it so that the debug lines aren't removed.

**Comment by DiegoCPB** [comment]
This should fix issue #135

**Comment by passingthru67** [comment]
@DiegoCPB I just merged your changes. Thanks for the assist.

**Pull request closed without merging**
